### ISSUE TITLE
The mod on modrinth is server only though it is client only

### ISSUE THREAD

**Issue by Cartrigger** [Roundaround/mc-fabric-elytra-swap#1]
![image](https://github.com/Roundaround/mc-fabric-elytra-swap/assets/81428538/633ccf78-9965-49f7-9d71-8ee44f2028e5)
![image](https://github.com/Roundaround/mc-fabric-elytra-swap/assets/81428538/2dd44b32-4f6a-46b7-a210-aae0d8e4e6cd)

**Comment by Roundaround** [comment]
While confusing, the labels here are actually correct, and they're more meant for multiplayer contexts anyway.

The names "client" and "server" in Minecraft mean slightly different things than they do in typical games. When you play single player, your game is actually starting a local server that only you can connect to. This is referring to that server.

What this means is that for single player, it just has to be installed on your local instance because that includes the integrated server automatically. For multiplayer, this mod actually has to be installed on the **server**, not on your client.
